<?php
/**
 * Created by PhpStorm.
 * User: saulo.desousa
 * Date: 4/29/14
 * Time: 12:31 PM
 */

?>

<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php $_renewableproductfilter = $this->getRenewableCustFilter(); ?>
<?php Mage::log('You have Reached the Filtered Collection');?>
<div class="box">

    <div class="entry-edit">

        <div class="entry-edit">


            <div class="page-title">
                <h1><?php echo 'Renewable Product - Customer List' ?></h1>
            </div>

            <?php echo $this->getPagerHtmladmin(); ?>

            <?php if($_renewableproductfilter->getSize()): ?>
                <table class="data-table" id="my-orders-table">

                    <tbody>
                    <?php $_odd = ''; ?>
                    <?php foreach ($_renewableproductfilter as $_renewablelist) { if ($_renewablelist->getActivestatefield() > 0){?>
                        <?php
                        $alert_yellow = 120;
                        $alert_orange = 60;
                        $alert_red = 30;
                        $minimumdatevalueprior = 60;
                        $fixeddate = strtotime(date('Y-m-d'));
                        $datetoexpire = strtotime($_renewablelist->getRenewalDate());
                        $dateresult = $datetoexpire - $fixeddate;
                        $days_remaining = floor($dateresult / 86400);
                        //                                $hours_remaining = floor(($dateresult % 86400) / 3600);
                        Mage::log('This is the fixeddate: '.$fixeddate.'  This is the datetoexpire: '.$datetoexpire.'  This is the result from the Fixeddate - daystoexpire: '.$days_remaining.' Date to Subtract:'.$dateresult);
                        ?>
                        <?php
                        $renewableprodid = $_renewablelist->getProdId();
                        $renewableproductcollection = Mage::getModel('catalog/product')->load($renewableprodid);
                        $renewable_product_url = $renewableproductcollection;
                        ?>
                        <thead>
                        <tr>
                            <th style="color: #000000; font-weight: bold; padding: 5px;"><?php echo $this->__('Trans#') ?></th>
                            <th style="color: #000000; font-weight: bold; padding: 5px;"><?php echo $this->__('Order#') ?></th>
                            <th style="color: #000000; font-weight: bold; padding: 5px;"><?php echo $this->__('Cust.ID#') ?></th>
                            <th style="color: #000000; font-weight: bold; padding: 5px;"><?php echo $this->__('Cust.Name') ?></th>
                            <th style="color: #000000; font-weight: bold; padding: 5px;"><?php echo $this->__('Prod.ID#') ?></th>
                            <th style="color: #000000; font-weight: bold; padding: 5px;"><?php echo $this->__('Product Name') ?></th>
                            <th style="color: #000000; font-weight: bold; padding: 5px;"><?php echo $this->__('Product Key#') ?></th>
                            <th style="color: #000000; font-weight: bold; padding: 5px;"><?php echo $this->__('Renewal Date :') ?></th>
                            <th style="color: #000000; font-weight: bold; padding: 5px;"><?php echo $this->__('Last Modified By:') ?></span></th>
                            <th style="color: #000000; font-weight: bold; padding: 5px;"><?php echo $this->__('L.D.M.') ?></span></th>
                            <th style="color: #000000; font-weight: bold; padding: 5px;"><?php echo $this->__('Days Left') ?></th>
                            <th style="color: #000000; font-weight: bold; padding: 5px; float: right;"><?php echo $this->__('Edit') ?></th>
                        </tr>
                        </thead>
                        <tr>
                            <td style="padding: 5px;"><?php echo $_renewablelist->/*these are the actual table fields ->*/ getRealOrderId() ?></td>
                            <td style="padding: 5px;"><?php echo $_renewablelist->/*these are the actual table fields ->*/ getActualOrderNumber() ?></td>
                            <td style="padding: 5px;"><?php echo $_renewablelist->/*these are the actual table fields ->*/ getRealCustId() ?></td>
                            <td style="padding: 5px;"><?php echo $_renewablelist->/*these are the actual table fields ->*/ getCustName() ?></span></td>
                            <td style="padding: 5px;"><?php echo $_renewablelist-> /*these are the actual table fields ->*/ getProdId() ?></td>
                            <td style="padding: 5px;"><?php echo $_renewablelist-> /*these are the actual table fields ->*/ getRealProdName() ? $this->htmlEscape($_renewablelist-> /*these are the actual table fields ->*/ getRealProdName()) : '&nbsp;' ?></td>
                            <td style="padding: 5px;"><?php echo $_renewablelist-> /*these are the actual table fields ->*/ getProdKey() ?></td>
                            <td style="padding: 5px;"><em><?php if ($_renewablelist->getRenewalDate() != '0000-00-00'){
                                        /*
                                         * This displays Renewal Date in the Client's Required Format i.e. = 01-Jan-2000
                                         * */
                                        echo date('d-M-Y', strtotime($_renewablelist->getRenewalDate()));
                                        /*
                                         * end
                                         * */
                                    }else{ ?><div style="color: #FF0000; text-align:center; "><strong><?php echo $this->__('Renewal Date yet to be Assigned');?></strong></div><?php }?></em>
                                <div class="link-reorder tiptip" style="color:#000000; display:inline; border-radius:2px; padding:3px 10px 3px 10px; background-color:
                                <?php
                                if($days_remaining >= $alert_yellow){
                                    Mage::log('Color '.$days_remaining);
                                    echo $this->__('#009900;" title="Good"');
                                }else if($days_remaining <= $alert_yellow && $days_remaining >= $alert_orange){
                                    echo $this->__('#FFFF00;" title="Moderate"');
                                }else if($days_remaining <= $alert_orange && $days_remaining >= $alert_red){
                                    echo $this->__('#FF9900;" title="Needs Attention"');
                                }else if($days_remaining <= $alert_red && $_renewablelist->getRenewalDate() != '0000-00-00' && $days_remaining != $alert_orange && $days_remaining != $alert_yellow){
                                    echo $this->__('#FF3300;" title="Renewal Needed / Has been Deactivated"');
                                }else{ echo 'none;"';}?> >

                                    </div>
                                    </td>
                                    <td style="padding: 5px;"><?php echo $_renewablelist->/*these are the actual table fields ->*/ getModifiedbyName() ?></td>
                            <td style="padding: 5px;"><?php echo $_renewablelist->/*these are the actual table fields ->*/ getLastDateModified(); ?></td>
                            <td  style="padding: 5px;" class="a-center"><?php if($_renewablelist->getRenewalDate() != '0000-00-00'){?>
                                <b style="color: #FF0000; font-size: 14pt;"><?php echo $days_remaining; ?></b>
                            </td>
                            <?php }else{ ?><div style="color: #FF0000; text-align:center; "><strong><?php echo $this->__('Days Unavailable');?></strong></div>
                            <?php } ?>
                            <td style="padding: 5px;">
                                <form method="get" id="contactForm" action="<?php echo Mage::getStoreConfig(Mage_Core_Model_Store::XML_PATH_SECURE_BASE_URL).'renewableprod/index/renewableprodedit'?>">
                                    <input type="hidden" name="transidedit" id="transidedit" value="<?php echo $_renewablelist->/*these are the actual table fields ->*/ getRealOrderId() ?>"/>
                                    <div class="buttons-set">
                                        <input type="text" name="hideit" id="hideit" value="" style="display:none !important;" />
                                        <button type="submit" title="<?php echo $this->__('Edit Owner/ Others') ?>" class="button"><span><span><?php echo $this->__('Edit Owner/ Others') ?></span></span></button>
                                    </div>
                                </form>
                            </td>
                        </tr>

                    <?php
                    }
                    }
                    ?>

                    </tbody>
                </table>
                <script type="text/javascript">decorateTable('my-orders-table');</script>
                <?php echo $this->getPagerHtmladmin(); ?>

            <?php endif ?>
            <!--            <div class="buttons-set">-->

            <!--                <a style="float: right;" title="--><?php //echo $this->__('Go Back') ?><!--" class="button"><span><span>-->
            <a style="text-decoration: none; color: #ffffff; margin-left: 95%; background-color: orange; padding:5px;" href="<?php echo Mage::getStoreConfig(Mage_Core_Model_Store::XML_PATH_SECURE_BASE_URL) . 'renewableprod/adminhtml_renewableprodlist/' ?>" title="<?php echo $this->__('Go Back') ?>" class="button"><?php echo $this->__('Go Back') ?></a>
            <!--                        </span></span></button>-->
            <!--            </div>-->
        </div>
    </div>
</div>
<!--<script type="text/javascript">-->
<!--    //<![CDATA[-->
<!--    var renewableprodeditownerandothersForm = new VarienForm('renewableprodeditownerandothersForm', true);-->
<!--    //]]>-->
<!--</script>-->